# 站点设定——
title: 无名汉化组
email: whuihuan@outlook.com
description: >
  没有最好，只有更好；无名汉化，因你存在！
baseurl: ""
url: "http://www.wmhhz.com"
permalink: none

# 自定义配置——

#字符串定义
string:
  topic2: 最新动态

#公告
topic:
  - title: 公告
    text: 1.官网恢复的差不多了，可以使用了<br>2.GTA3暂不提供汉化下载，正在调试新版汉化<br>3.下载GTASA汉化请去项目页<br>交流群：<b>5646840</b>←仅此一个交流群<br>欲加入汉化组请联系QQ:<b>1651088879</b>

#动态
topic2:
  - title: 【2016/06/19】网站恢复完成，欢迎使用
    text: /news/news2
  - title: 【2016/06/10】网站恢复中
    text: /news/news1
  - title: 查看更多动态
    text: /news

# 全局设定——
timezone: Asia/Shanghai
encoding: UTF-8

# 编译设定——
markdown: kramdown

# 服务器设定——
host: 0.0.0.0
port: 14342