# 站点设定——
title: 无名汉化组
email: whuihuan@outlook.com
description: >
  没有最好，只有更好；无名汉化，因你存在！
baseurl: ""
url: "http://www.wmhhz.com"
permalink: none

# 自定义配置——

#字符串定义
string:
  topic2: 最新动态
  weibo: 微博

#公告
topic:
  - title: 公告
    text: 欢迎进入无名汉化组官网
  - title: 通知
    text: 1.官网正在改版中<br>2.汉化正在准备发布<br>3.网站暂时不能使用，等待下一次更新

#动态
topic2:
  - title: 【2016/06/10】网站恢复中 
    text: /news/news1
  - title: 【2016/06/10】网站恢复中 
    text: /news/news1
  - title: 查看更多动态
    text: /news

# 全局设定——
timezone: Asia/Shanghai
encoding: UTF-8

# 编译设定——
markdown: kramdown

# 服务器设定——
host: 0.0.0.0
port: 14342