# 站点设定
title: 无名汉化组
email: whuihuan@outlook.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.wmhhz.com"
permalink: none

# 自定义配置
author:
  name: 砕月
  weibo: 威严的审判长四季映姬

string:
  topic2: 最新动态
  
topic:
  - title: 公告
    text: 欢迎进入无名汉化组官网
  - title: 通知
    text: 汉化发布
    
topic2:
  - title: 【2014/08/05】GTASA、GTAIII都发布汉化新版本啦 
    text: /news3
  - title: 【2014/07/24】侠盗猎车手3汉化将于下月发布 
    text: /news2

# 全局设定
timezone: Asia/Shanghai
encoding: UTF-8

# 编译设定
markdown: kramdown

# 服务器设定
host: 0.0.0.0
port: 14342